version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Madrid
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Madrid
    open-pull-requests-limit: 99
